#+STARTUP: overview indent
#+TITLE: UFRGS TeX Users Group (UTUG)

* Apresentação do conteúdo

Estes arquivos compõem o pacote de estilos LaTeX de documentos para o
Instituto de Informática da Universidade Federal do Rio Grande do Sul
(INF/UFRGS). Várias classes de documentos são disponibilizadas, como
por exemplo:

- [[./inputs/iiufrgs.cls]], para documentos do tipo TI, dissertacao, tese, etc
- [[./inputs/sa.cls]], para produzir artigos para o Seminário de Andamento
- [[./inputs/iiletter.cls]], para produzir cartas com logotípos do II, em duas versões
- [[./slides/]], para criar apresentações com o estilo INF/UFRGS

Cada uma tem um arquivo de exemplo, no diretório [[./exemplos]].

* Participação

Comentários e sugestões são *MUITO* bem-vindos. Envie-os para a lista de
discussões do grupo de usuários TeX da UFRGS
(=utug-l@inf.ufrgs.br=). Para cadastrar-se na lista, visite o [[https://listas.inf.ufrgs.br/mailman/listinfo/utug-l][site da
lista de difusão]], ou envie e-mail para =utug-l-request@inf.ufrgs.br= com
a palavra =subscribe= no corpo da mensagem. Notem que a lista tem sido
bem pouco utilizada ultimamente, mas é o melhor meio de se comunicar
com a comunidade. Sua participação pode ser através de issues neste
site.

* Instalação

Os arquivos necessários para compilar os fontes tex encontram-se no
diretório [[./inputs]]. Copie todos os arquivos para o diretório do seu
documento ou utilize o =Makefile= para outras opções.
